name: Build Symfony

on:
  push:
    branches: [ master ]

jobs:
  FTP-Deploy-Action:
      runs-on: ubuntu-latest

      steps:
      - uses: actions/checkout@v2

      - name: Make envfile
        uses: SpicyPizza/create-envfile@v1
        with:
          env_keys:
            INPUT_ENVKEY_APP_ENV: 'prod'
            INPUT_ENVKEY_APP_DEBUG: '0'
            INPUT_ENVKEY_DATABASE_URL: ${{ secrets.DB_URL }}
            INPUT_ENVKEY_APP_SECRET: ${{ secrets.APP_SECRET }}
            INPUT_ENVKEY_VAR_DUMPER_FORMAT: 'html'
          file_name: .env


      - name: Install Composer
        run: composer install --no-dev --optimize-autoloader


      - name: Generate Cache
        run: composer dump-autoload --optimize --no-dev --classmap-authoritative

      - name: warmup chache
        run: php bin/console cache:warmup --env=prod
      
      - name: List output files
        run: find var/ -print


