name: Build Symfony

on:
  push:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: set environment variables
      uses: allenevans/set-env@v1.0.0
      with:
        APP_ENV: 'prod'
        APP_DEBUg: '0'
          
    - name: Install Composer
      run: composer install --no-dev --optimize-autoloader
      
    - name: Generate Cache
      run: composer dump-autoload --optimize --no-dev --classmap-authoritative

    - name: warmup chache
      run: php bin/console cache:warmup --env=prod
